name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg version=$(cat VERSION) --tag bitsler/docker-openeth:$(cat VERSION) --tag bitsler/docker-openeth:latest

    - name: Log into registry
      run: echo "${{ secrets.HUB_TOKEN }}" | docker login -u ${{ secrets.HUB_USERNAME }} --password-stdin

    - name: Push image
      run: |
          docker push bitsler/docker-openeth:$(cat VERSION)
          docker push bitsler/docker-openeth:latest

    - name: Push releases
      run: bash ./release.sh $(cat VERSION)


